[workspace]
authors = ["zylu <luzeyu3077@gmail.com>"]
channels = ["conda-forge"]
name = "pixi-hello"
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
hello = "python scripts/demo.py"
rebuild = "pip install -e . --no-deps --force-reinstall --no-build-isolation"

[dependencies]
python = ">=3.12,<3.13"
pip = "*"
setuptools = "*"
c-compiler = "*"

[pypi-dependencies]
pixi-hello = { path = ".", editable = true }
