[workspace]
authors = ["zylu <luzeyu3077@gmail.com>"]
channels = ["conda-forge"]
name = "pixi-hello"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
hello = "python demo.py"

[dependencies]
python = ">=3.12,<3.13"
pip = "*"
setuptools = "*"
wheel = "*"
c-compiler = "*"

[pypi-dependencies]
pixi-hello = { path = ".", editable = true }
